# Generated by Django 3.1.3 on 2020-11-08 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
