# Generated by Django 3.1.3 on 2020-11-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_minamount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(verbose_name=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='minamount',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
